### ISSUE TITLE
Samples do not work anymore

### ISSUE THREAD

**Issue by runningonfumes** [spring-cloud/spring-cloud-stream-samples#105]
When running the examples an error is shown at startup

`
Failed to bind properties under 'spring.cloud.stream.bindings.input.consumer' to org.springframework.cloud.stream.binder.ConsumerProperties:

    Property: spring.cloud.stream.bindings.input.consumer
    Value: 
    Origin: class path resource [application.yml]:4:12
    Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.cloud.stream.binder.ConsumerProperties]

Action:

Update your application's configuration
`

**Comment by highsmallxu** [comment]
I have the same problem. Please let us know how to solve it.

**Comment by sabbyanandan** [comment]
@runningonfumes: What sample are you running? Can you elaborate on the steps and the observation?

**Comment by runningonfumes** [comment]
An example is kafka.streams.dlq.sample.KafkaStreamsDlqSample (spring-cloud-stream-samples/kafka-streams-samples/kafka-streams-dlq-sample/src/main/java/kafka/streams/dlq/sample/KafkaStreamsDlqSample.java)

When I try to run that example (in Intellij), an error like mentioned is given and the program stops.

**Comment by sobychacko** [comment]
@runningonfumes Please try the latest samples. We had to do some cleanup in the yaml configuration. Thanks for reporting this.

**Comment by sobychacko** [comment]
@runningonfumes Did you get a chance to verify the sample?

**Comment by sobychacko** [comment]
Thanks for confirming. Closing the issue.
