### ISSUE TITLE
kafka-streams-aggregate application doesnt start

### ISSUE THREAD

**Issue by mwesox** [spring-cloud/spring-cloud-stream-samples#108]
The application doesnt start. 

`Description:  Failed to bind properties under 'spring.cloud.stream.bindings.input.consumer' to org.springframework.cloud.stream.binder.ConsumerProperties:      Property: spring.cloud.stream.bindings.input.consumer     Value:      Origin: class path resource [application.yml]:4:12     Reason: No converter found capable of converting from type [java.lang.String] to type [org.springframework.cloud.stream.binder.ConsumerProperties]  Action:  Update your application's configuration`

**Comment by sobychacko** [comment]
@mwesox This issue is resolved.
