### ISSUE TITLE
Unit testing Kafka Streams Samples example

### ISSUE THREAD

**Issue by 3ygun** [spring-cloud/spring-cloud-stream-samples#110]
# What?

For the [Kafka Streams Samples](/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples) there aren't example unit tests for the classes which use `KSteam` or `KTable`. Request is to add some.

# Which examples?

Tests for all of the following would be good:

1.  `KStream` in and `KStream` out (e.g. Testing the [Word Count](/kafka-streams-samples/kafka-streams-word-count))
1. `KStream` producer
1. `KStream` sink
1. Multiple `KStream` inputs and outputs
1. `KTable`
    - Input
    - Output
    - Sink & Producer

Thanks!

People asking similar questions:
- https://stackoverflow.com/questions/51048709/can-spring-cloud-stream-testsupportbinder-be-used-to-test-a-kafka-streams-proces

**Comment by 3ygun** [comment]
Testing sample added after this ticket: https://github.com/spring-cloud/spring-cloud-stream-samples/commit/e6cf1085a631a032edbefcbc7cfce1c9f82465d7

**Comment by sobychacko** [comment]
@3ygun The commit you mentioned require embedded Kafka for integration testing. We will still try to add examples of unit testing with this issue. In the meantime, if you want to contribute a PR for this, you are very welcomed. Thanks.

**Comment by jukkakarvanen** [comment]
PR #144 is Example Unit Test of KafkaStreamsWordCountApplication.WordCountProcessorApplication using TopologyTestDriver

**Comment by sabbyanandan** [comment]
Addressed in https://github.com/spring-cloud/spring-cloud-stream-samples/pull/144.
