### ISSUE TITLE
KTable as input binding doesn't work if @input is not specified at parameter level

### ISSUE THREAD

**Issue by tambre** [spring-cloud/spring-cloud-stream-samples#111]
For KStream we can specify binding as 

@StreamListener("input")
public void process (KStream<?,?> inputStream)

However, this doesnt work for KTable. Throws Illegal Argument Exception "Method must be declarative". I had to explicitly specify as follows to make the binding work. 

@StreamListener
public void process(@Input("input") KTable<?,?> inputTable)

is this expected behavior?

**Comment by sobychacko** [comment]
@tambre Can you give more details? Maybe a full code snippet such as your usage of `EnableBinding` etc.

**Comment by tambre** [comment]
This works:

`@EnableBinding(TradeMsgReaderTopics.class)
public class TradeMsgReaderProcessor
{
    private static final Logger logger = LoggerFactory.getLogger(TradeMsgReaderProcessor.class);

    @StreamListener
    public void process(@Input(TradeMsgReaderTopics.INPUT) KTable<String, TradeMessageEvent> inputTable)
    {
        inputTable.toStream().foreach((key, value) -> logger.debug("key: {} :: value: {}", key, value));
    }
}
`

**Comment by tambre** [comment]
This didn't work:

`@EnableBinding(TradeMsgReaderTopics.class)
public class TradeMsgReaderProcessor
{
    private static final Logger logger = LoggerFactory.getLogger(TradeMsgReaderProcessor.class);

    @StreamListener(TradeMsgReaderTopics.INPUT)
    public void process(KTable<String, TradeMessageEvent> inputTable)
    {
        inputTable.toStream().foreach((key, value) -> logger.debug("key: {} :: value: {}", key, value));
    }
}
`

**Comment by tambre** [comment]
The binding interface is

`@Configuration
public interface TradeMsgReaderTopics
{
    String INPUT = "tradeMsgEventStore";

    @Input("tradeMsgEventStore")
    KTable<String, TradeMessageEvent> tradeMsgEventStore();

}`

**Comment by sobychacko** [comment]
@tambre Do you mind creating an issue in the main binder [repository](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka)? This looks like a bug. We will take a further look.

**Comment by tambre** [comment]
sure. thanks

**Comment by sabbyanandan** [comment]
Fixed in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/24551d6e6dbf31706afa63a0e5d57bc4861a90af.
