### ISSUE TITLE
Typo in application.yml 

### ISSUE THREAD

**Issue by rodneygp** [spring-cloud/spring-cloud-stream-samples#116]
spring-cloud-stream-samples/master/kafka-streams-samples/kafka-streams-interactive-query-basic/src/main/resources/application.yml:

spring.applica **_it_** on.name: should be spring.applica **_ti_** on.name.

**Comment by ablx** [comment]
See https://github.com/spring-cloud/spring-cloud-stream-samples/commit/ce0e8e1e1893ce29b741ce0361dd727c2a411b21
