### ISSUE TITLE
KafkaStreamsWordCountApplication failing with java.lang.ClassCastException: kafka.streams.word.count.KafkaStreamsWordCountApplication$WordCount cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by codependent** [spring-cloud/spring-cloud-stream-samples#149]
After the latest upgrade of the libraries to Spring Boot 2.2.0-SNAPSHOT and `<spring-cloud-stream.version>Horsham.BUILD-SNAPSHOT</spring-cloud-stream.version>` the KafkaStreamsWordCountApplication fails, as can be seen in the tests:

```
Caused by: java.lang.ClassCastException: kafka.streams.word.count.KafkaStreamsWordCountApplication$WordCount cannot be cast to java.lang.String
        at org.apache.kafka.common.serialization.StringSerializer.serialize(StringSerializer.java:28)
        at org.apache.kafka.common.serialization.Serializer.serialize(Serializer.java:60)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:162)
        at org.apache.kafka.streams.processor.internals.RecordCollectorImpl.send(RecordCollectorImpl.java:102)
        at org.apache.kafka.streams.processor.internals.SinkNode.process(SinkNode.java:89)
        ... 32 more
```

The error happens after this map operation, before writing to the sink:

```
.map((key, value) -> new KeyValue<>(null, new WordCount(key.key(), value, new Date(key.window().start()), new Date(key.window().end()))));
```

I've tried with a previous version that worked and the topology included a mapvalues node that converted the WordCount object value to a byte array,:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/6399869/59443286-fcda8d80-8dfb-11e9-916d-c4ecf707ea5f.png">

The current topology doesn't show that mapvalues processor anymore:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/6399869/59443610-8d18d280-8dfc-11e9-9bd6-c97087df881c.png">

**Comment by sobychacko** [comment]
@codependent I am working on this [issue](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/651) in core binder. Things are still a bit in flux and I have a few more PR's coming after this. By the end of today, I am hoping to fix these. Thanks for pointing this out.

**Comment by codependent** [comment]
The shipping-service kstream in kafka-e2e-kotlin-sample is crashing when reading from the customer topic, I guess this must be related to the issue you're working on:

```
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```

Just let me know if I can help out.

**Comment by sobychacko** [comment]
Ok, I will have a look soon.

**Comment by sobychacko** [comment]
@codependent New changes went into core binder for native Serde changes and inferring `Serdes` on input/output as much as possible. I cleaned up all the Kafka Streams samples to reflect the changes. I ran your Kotlin sample locally and it runs as expected.

Here is the gist of the Serde changes that went into the master. These changes will only be available on the 3.0 (Horsham) line of Spring Cloud Stream and won't be backported. 

1. Binder now uses native Serde as the default serialization and deserialization strategy for input and output bindings. 
2. Applications have to explicitly set `useNativeDecoding` and `useNativeEncoding` to `false` to force the conversion done by the framework. 
3. When using the default native conversion by Kafka Streams, applications don't need to set `Serdes` used on key/value types if those types map to one of the following:
* Integer
* Float
* Double
* Long
* Short
* byte[]
* String

If none of these matches, it defaults to `JsonSerde` provided by spring-kafka. If the application explicitly provides a `Serde` on the binding, then that gets precedence always. If the application uses `Serde` objects like Confluent's Avro Serde, then that has to be set explicitly on the configuration.

These changes will also significantly reduce the topology depth of Spring Cloud Stream/Kafka Streams applications that you once reported on [SO](https://stackoverflow.com/questions/55929162/spring-cloud-stream-generates-unnecessary-complex-kafka-topologies-why). 

Once you confirm that things are working as expected, we can close this issue.

**Comment by codependent** [comment]
@sobychacko The 3.0.0 release will be awesome, I'm looking forward to migrating my apps to it.

I've checked that the Kotlin sample works ok. There's still a thing I don't understand though:

The customer and order producers use the Spring Cloud Stream serializer (not the native one), and that's why you explicitly disabled the native decoding in shipping service, according to the new behaviour, so far so good:

```
spring.cloud.stream.bindings.input.consumer.useNativeDecoding: false
spring.cloud.stream.bindings.order.consumer.useNativeDecoding: false
spring.cloud.stream.bindings.output.producer.useNativeEncoding: false
``` 

The point is you commented out this binding config:

```
#          bindings:
#            input:
#              consumer:
#                valueSerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
```

Having a look a it, in fact it's wrong, it should've been `binding.order.consumer...`, so I guess it wasn't actually doing anything and could be removed.

My question is how does the framework know how to deserialize `orderEvent: KStream<Int, GenericRecord>` being an `io.confluent.kafka.streams.serdes.avro.GenericAvroSerde`??

**Comment by codependent** [comment]
Regarding Spring Cloud Stream Producers/Consumer... I'd like to point out that it's kind of confusing that they still have `useNativeEncoding/Decoding: true` as default, whereas Spring Cloud Stream Kafka Streams applications default to the contrary `useNativeEncoding/Decoding: false`.

Maybe it's worth adding an outstanding box stressing this in the docs.

**Comment by codependent** [comment]
What's weird is... I've modified the customer Producer to use the native encoding:

```
spring:
  application:
    name: customer-service
  cloud:
    stream:
      kafka:
        bindings:
          output:
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.IntegerSerializer
                value:
                  serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
                schema:
                  registry:
                    url: http://localhost:8081
      bindings:
        output:
          destination: customer
          contentType: application/*+avro
          producer:
            useNativeEncoding: true
      schema-registry-client:
        endpoint: http://localhost:8081

server:
  port: 8084
```

This is the before and after of the messages produced:

**Spring Cloud Stream serialization:**

```
Key (4 bytes): 
  Value (21 bytes): John DoeElm Street
  Timestamp: 1560935605105
  Partition: 0
  Offset: 8
  Headers: contentType="application/vnd.customer.v1+avro",spring_json_header_types={"contentType":"java.lang.String"}
``

**Spring Cloud Stream serialization disabled:**
```
Key (4 bytes): 
  Value (26 bytes):John DoeElm Street
  Timestamp: 1560935995841
  Partition: 0
  Offset: 9
  Headers: 
```

However the shipping service, despite having `spring.cloud.stream.bindings.input.consumer.useNativeDecoding: false` is able to consume both types of messages without any problem. How come???

**Comment by sobychacko** [comment]
@codependent I will try to answer the 3 comments you posted above here. 

1. We can certainly remove that `GenericAvroSede` configuration from the shipping service configuration as that is not used. 
2. Without enough documentation and communication around this, it could be confusing that the regular Kafka binder sets `useNativeDecoding/useNativeEncoding` properties to be `false` and the Kafka Streams binder sets them to `true` by default. We should certainly improve the docs for 3.0 on this matter. There are some important benefits of switching these to `true` by default in the Kafka Streams binder though. 

    * It reduces the topology depth that the Kafka Streams applications generate (as you pointed out in the SO thread) and that alone is a big win in my opinion. 
   * Most Kafka Streams application developers are already familiar with the concept of `Serdes` and we don't really need to mix the `ScSt` converters unless there is a need. The only time we need to use the `ScSt` converters in Kafka Streams app (Setting native decoding to `false`) is when the producers use a specific serializer that the consumer cannot deserialize. For example, as in your case, the producer uses the `ScSt` provided Avro converter and thus the consumer must use a compatible deserializer. In all the other cases, we can rely on `Serde` on the input and output (edges of the application). But I totally agree, we need to improve the docs on this.

3. In the following configuration, setting `useNativeEncoding` to true on the output binding does not have any effect as that is only applicable for Kafka Streams application and this is a regular Kafka binder application. So, in both cases, you are simply using the `ScSt` provided converter using the avro content type.
```
bindings:
        output:
          destination: customer
          contentType: application/*+avro
          producer:
            useNativeEncoding: true
```

**Comment by sobychacko** [comment]
btw, did you verify that the topology depth is now much reduced?

**Comment by codependent** [comment]
> In the following configuration, setting useNativeEncoding to true on the output binding does not have any effect as that is only applicable for Kafka Streams application and this is a regular Kafka binder application. So, in both cases, you are simply using the ScSt provided converter using the avro content type.

Actually the modified producer is producing records with a native serializer. I realized the shipping-service reads the messages but the fields are empty since it doesn't know the actual schema (which is perfectly right since there are no headers). So no more doubts regarding this matter.

> btw, did you verify that the topology depth is now much reduced?

Unfortunatelly the shipping-service isn't using the native decoding/encoding so it can't take advantage of your improvements. The topology keeps being kind of crazy. Oddly enough there are a number of processors that doesn't seem to make any sense (or at least I don't understand their usage such as KSTREAM-PROCESSOR-0000000002, KSTREAM-PROCESSOR-0000000006, KSTREAM-PROCESSOR-0000000026, etc. ending in a dead end):

![index](https://user-images.githubusercontent.com/6399869/59803608-417a9300-92ec-11e9-938b-4cff80ed64be.jpg)

**Comment by sobychacko** [comment]
@codependent You are right. In order to make use of the native Serde improvements, the application has to use the default native serde settings. In your app, you have to use the framework provided one and you will still end up with that deeper topology. I will look into why it generates that many (seemingly unnecessary) branches. If your producer could end up using the same Avro serializers that the shipping service uses, then you can switch to native decoding on the shipping service, but at the moment this is not possible since the schema registry client does not give an option to configure the serializer. I will try to make some improvements in the schema registry support so that, it can use other avro serializers. I will keep you posted.

**Comment by codependent** [comment]
Awesome, I'll wait for your news. 

Do you think we should rename this issue of close it and open a new one?

**Comment by sobychacko** [comment]
That sounds like a good plan. Feel free to close this and open another one.
