### ISSUE TITLE
Switch to Function-based samples

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-samples#156]

**Comment by sabareeshkkanan** [comment]
While functions are lot of fun but as of now they are limited to only one processor per service, which is very limiting in real world scenarios. Does it support condition such as this ?
`    @StreamListener(value = EvenOddProcessor.INPUT, condition = "headers['type']=='even'")`

**Comment by olegz** [comment]
@sabareeshkkanan that is not true at all. Functional model is feature compatible (and then some) with annotation-based model including routing. Please see https://cloud.spring.io/spring-cloud-static/spring-cloud-stream/3.0.0.RC1/reference/html/spring-cloud-stream.html#_content_based_routing_with_functions and let us know if you have any questions

**Comment by olegz** [comment]
Here is the complete sample:
```
@SpringBootApplication
public class RoutingStreamApplication {

	public static void main(String[] args) {
		SpringApplication.run(RoutingStreamApplication.class,
				"--spring.cloud.stream.function.routing.enabled=true",
				"--spring.cloud.function.routing-expression=headers['type']=='even' ? 'even' : 'odd'");
	}

	@Bean
	public Consumer<Integer> even() {
		return value -> {
			System.out.println("EVEN: " + value);
		};
	}

	@Bean
	public Consumer<Integer> odd() {
		return value -> {
			System.out.println("ODD: " + value);
		};
	}
}
```
There are actually more dynamic ways as well, and it is explained in the docs. So in other words routing (conditional) support for functional programming model is much richer

**Comment by sabareeshkkanan** [comment]
@olegz I saw your presentation at Spring One, pretty impressed with the progress on this area. Since the presentation I was trying to build a demo but not successful yet. Can you point me to a working sample with more than one processor.

**Comment by olegz** [comment]
I am not sure what you're asking as I just posted a complete sample above. And if it's about routing here is more information https://github.com/spring-cloud/spring-cloud-stream/blob/master/docs/src/main/asciidoc/spring-cloud-stream.adoc#routing-with-functions
Perhaps you can elaborate on some details of what issues are you having?

**Comment by sobychacko** [comment]
@dsibilio Did you get a chance to check this blog out? https://spring.io/blog/2019/11/04/spring-cloud-stream-composed-functions-or-eip. It has more information about composing functions.
