### ISSUE TITLE
Inspite of having pointing to two different EventHubs the Group Coordinator is always single cluster

### ISSUE THREAD

**Issue by ignesious** [spring-cloud/spring-cloud-stream-samples#157]
Answer: Spring cloud stream allows to consume messages form two different topic on two different cluster.

Find below spring properties:-  
```
spring.cloud.stream.binders.kafka-qa1.type=kafka spring.cloud.stream.binders.kafka-qa1.environment.spring.cloud.stream.kafka.binder.brokers=First:9093 spring.cloud.stream.binders.kafka-qa1.environment.spring.cloud.stream.kafka.binder.configuration.security.protocol=SASL_SSL spring.cloud.stream.binders.kafka-qa1.environment.spring.cloud.stream.kafka.binder.configuration.sasl.mechanism=PLAIN spring.cloud.stream.binders.kafka-qa1.environment.spring.cloud.stream.kafka.binder.autoCreateTopics=false spring.cloud.stream.binders.kafka-qa1.environment.spring.cloud.stream.kafka.binder.jaas.loginModule=org.apache.kafka.common.security.plain.PlainLoginModule spring.cloud.stream.binders.kafka-qa1.environment.spring.cloud.stream.kafka.binder.jaas.options.username=$ConnectionString spring.cloud.stream.binders.kafka-qa1.environment.spring.cloud.stream.kafka.binder.jaas.options.password=password  spring.cloud.stream.binders.kafka-qa2.type=kafka spring.cloud.stream.binders.kafka-qa2.environment.spring.cloud.stream.kafka.binder.brokers=server2:9093 spring.cloud.stream.binders.kafka-qa2.environment.spring.cloud.stream.kafka.binder.configuration.security.protocol=SASL_SSL spring.cloud.stream.binders.kafka-qa2.environment.spring.cloud.stream.kafka.binder.configuration.sasl.mechanism=PLAIN spring.cloud.stream.binders.kafka-qa2.environment.spring.cloud.stream.kafka.binder.autoCreateTopics=false spring.cloud.stream.binders.kafka-qa2.environment.spring.cloud.stream.kafka.binder.jaas.loginModule=org.apache.kafka.common.security.plain.PlainLoginModule spring.cloud.stream.binders.kafka-qa2.environment.spring.cloud.stream.kafka.binder.jaas.options.username=$ConnectionString spring.cloud.stream.binders.kafka-qa2.environment.spring.cloud.stream.kafka.binder.jaas.options.password=password2
```

 Here Kakfa- QA1 points to cluster one  and Kafka-QA2 points to cluster two.  While listening from these two different cluster given two different topics which exists on these clusters.  Expected :- Spring cloud stream should listen from these two different topic from two cluster  Actual :- Only one of the cluster is identified as Group Coordinator, and since even though the topic exists in other cluster its getting created in the cluster which is chosen as Group Coordinator. 

So on testing with two streams  [Consumer clientId=consumer-3, groupId=db2_cosmos_store_success] **Discovered group coordinator ap-fds-receiving-store-1.servicebus.windows.net:9093** (id: 2147483647 rack: null) [Consumer clientId=consumer-6, groupId=wh_db2sync_receive_success] **Discovered group coordinator ap-fds-receiving-store-1.servicebus.windows.net:9093** (id: 2147483647 rack: null)  
 For both the consumers its discovering only one as group coordinator hence the issue.   
This is occuring only on event hub. In localhost with kafka its not appearing.

Sorry for reaching wrong forum but if anyone has any idea let me know please.

**Comment by sabbyanandan** [comment]
Hi, @ignesious. It appears you're trying to use the Kafka binder, but against Event Hubs. We don't support this type of application in the samples repo here, so I'd suggest opening a StackOverflow thread with a reproducible sample, so folks familiar with EventHubs can review and help out.
