### ISSUE TITLE
Error: java.lang.ClassCastException: com.example.avro.AvroClearingScenarioCopy  cannot be cast to com.example.avro.AvroClearingScenarioCopy

### ISSUE THREAD

**Issue by ylcolala** [spring-cloud/spring-cloud-stream-samples#170]
Context:
 Spring Cloud Stream + Kafka streams +confluent schema registry 5.2.2 + Spring cloud dependency version Hoxton.RELEASE

My configuration:
 
![image](https://user-images.githubusercontent.com/3927813/70152741-ba2daa00-16e8-11ea-9468-2c53af0544be.png)

Error details:
![image](https://user-images.githubusercontent.com/3927813/70152865-e77a5800-16e8-11ea-946c-bb526ac18fc9.png)

Actually, I followed the spring cloud stream kafka stream example.
There is still an error.
How can I fix it?
Thank you very much.

**Comment by ylcolala** [comment]
By the way, if I use input->input.print(printed.tosysout()), it can show the avro data. however, any other operations like mapValues throw this exception.  And I code kafka stream without spring cloud stream to pull the topic, it works.

**Comment by sobychacko** [comment]
@ylcolala Can you provide a small sample where we can run and reproduce the issue?

**Comment by ylcolala** [comment]
I recode the project without my old project code. And it works. So I guess it's a version confliction. And I will migrate my old project code to new project which it works, step by step. Thank you for you help anyway. Now I close the issue.
