### ISSUE TITLE
Very bad samples

### ISSUE THREAD

**Issue by sureshachary** [spring-cloud/spring-cloud-stream-samples#176]
All very bad and crude samples.
I doubt whether this has been created for people to use or not.
None of the samples are useful.
The author just plays around with a useless Senor.
Why cant they just take an employee, department, address like simple example.
Documentation is pathetic.
None is clear and complete.

**Comment by sobychacko** [comment]
@sureshachary Could you please be more specific? What exact application are you talking about here? Taking a cue from the description you have given, you might be trying the schema registry samples. All these samples are based on contrived use cases and they can be run standalone for the most part. In addition, this is an open-source project that is community-driven.  You are more than welcomed to provide your feedback and improvements through pull requests. Thank you!

**Comment by olegz** [comment]
Your comments are clear example of how not to behave in Open Source community. Rude,  obnoxious and unsubstantiated comments like these are counter to the basic principles of open source, open community and open collaboration. 

Further more they are highly disrespectful to all the members of this open source community who contribute their own time to make them better.

While these samples may not be perfect, they have helped thousands of developers world wide to get started and we constantly doing our best by incorporating community feedback. 

Your comments hardly constitute an actionable feedback, therefore I am closing this issue with no further action to be taken.

**Comment by sureshachary** [comment]
@olegz @sobychacko My comments are not rude. Those are the reflections of helpless of an open source user. In the last one month, I've spent enough time on Github related to Spring Cloud Stream and Spring Cloud Schema Registry. But I couldn't find any good samples or documentation related to both by its creators itself. A better example would be to get a third person and review the Schema Registry Server documentation. There are many instances like this, but what to do, when we poor users react when we dont get what we bare minimum needed, it is flagged as "RUDE"

**Comment by olegz** [comment]
Your comments are actually extremely rude, uncouth and somewhat offensive as you're showing complete disrespect to the effort and time the community put into creating these samples.
You are accusing author(s) without substance:
- in creating "not useful samples" - when they actually have helped thousands of people 
- of "plays around with a useless Senor"
- that "Documentation is pathetic"

. . . need I continue?

There are ways and tone to express the hardships and misunderstandings you may be having and it's not the way to do it. 
The way to do it would be something like:
_Hi, I am trying to do . . . . and I am having some issues. I have read documentation <link> and still having problems figuring out so and so. . . etc_

**Comment by sureshachary** [comment]
@olegz If you read those comments with a prejudiced mind that the comments are rude, then I can't help it. I expressed my helplessness. Calm down and read it again as a comment and not an expression of anger. 

People have different ways of expressing their concerns. All are not same and you cannot expect all to be the same you want to be! 

Comments are not always soothing and welcoming. Though its opensource, the creators should be willing to accept negative comments on their creations. @sobychacko understood that and he clearly and calmly replied to my comment, but you took in another way and you felt it rude. Thats why I said people are different.

Also, here I didn't pin-point any person or wrote anything personally. It was on the Content I commented and not anybody on a personal side. Hope you understand that.

**Comment by mammenj** [comment]
@sureshachary your comments are not only rude but ignorant as well. Open source community does not owe you or anyone to create samples. 
May be you need to specify your case and others may help. Also if you have nothing to contribute, then don't but don't demotivate others who  contribute. Cheers!

**Comment by sureshachary** [comment]
I very well know that open source community does not owe anything to anyone and I'm not demotivating anyone. My comments does not point to that. But the truth is; what it is not there, is not there, thats it.  I don't think the committers of Spring community or any community will get demotivated with a negative comment. Negative comments should be taken as a opportunity to fill the gaps and not pointing the commenter and flag it was rude.

Well, this chapter stands closed for me.
