### ISSUE TITLE
Create example showing custom message sending

### ISSUE THREAD

**Issue by sokie** [spring-cloud/spring-cloud-stream-samples#18]
As a first time spring cloud stream user I would like to know how to send a custom message to a queue after a certain event/request and not using a poller.
I will provide a pull-request with this issue.

**Comment by sokie** [comment]
Pull request done https://github.com/spring-cloud/spring-cloud-stream-samples/pull/19
Feel free to discuss :)

**Comment by sabbyanandan** [comment]
Stale issue; closing it.
