### ISSUE TITLE
Pause Kafka Consumer with Functional Style

### ISSUE THREAD

**Issue by AttitudeL** [spring-cloud/spring-cloud-stream-samples#199]
Dear Developers,

Please allow me to apologize of posting question here. I know this isn't the right place however given that I've lost 100 of my stackoverflow reputation for bounty for this very same question https://stackoverflow.com/questions/66123464/pause-kafka-consumer-with-spring-cloud-stream-and-functional-style, I believe that I earned some credit for posting such question here.

I'm trying to build a retry mechanism which pauses the consumer on the retry topic based on the timestamp and retry count from the incoming message. This requires me to get the header information that includes the consumer, topic and partition information.

With classic style I can do the following.
```
@StreamListener(Sink.INPUT)
public void in(String in, @Header(KafkaHeaders.CONSUMER) Consumer<?, ?> consumer) {
    System.out.println(in);
    consumer.pause(Collections.singleton(new TopicPartition("myTopic", 0)));
}
```

However I cannot find any example or documentation showing the functional style.
I have tried the following but it doesn't work.
```
@Bean
public Function<Message<?>, KStream<String, String>> process() {
    message -> {
        Consumer<?, ?> consumer = message.getHeaders().get(KafkaHeaders.Consumer, Consumer.class);
        String topic = message.getHeaders().get(KafkaHeaders.Topic, String.class);
        Integer partitionId = message.getHeaders().get(KafkaHeaders.RECEIVED_PARTITION_ID, Integer.class);
        CustomPayload payload = (CustomPayload) message.getPayload();
        if (payload.getRetryTime() < System.currentTimeMillis()) {
            consumer.pause(Collections.singleton(new TopicPartition(topic, partitionId)));
        }
    }
}
```

I got such exception.
```
Caused by: java.lang.IllegalStateException: No factory found for binding target type: org.springframework.messaging.Message among registered factories: channelFactory,messageSourceFactory,kStreamBoundElementFactory,kTableBoundElementFactory,globalKTableBoundElementFactory
    at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.getBindingTargetFactory(AbstractBindableProxyFactory.java:82)
    at org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsBindableProxyFactory.bindInput(KafkaStreamsBindableProxyFactory.java:191)
    at org.springframework.cloud.stream.binder.kafka.streams.function.KafkaStreamsBindableProxyFactory.afterPropertiesSet(KafkaStreamsBindableProxyFactory.java:111)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
    ... 96 more
```

It would be great if someone can point me at the right direction of solving this problem. I really liked the functional style and I don't want to mix the code with both functional and classic binding (which also has many annotations marked as deprecation).

Much appreciated!

**Comment by sobychacko** [comment]
Hi, @AttitudeL Sorry, we missed your question on StackOverflow. Once we figure this out, we can update the SO question with an answer as well. The functional example you showed above contains `KStream`. Is that intentional? From your `StreamListener` example, it doesn't look like you are using the Kafka Streams binder, but the regular message channel-based Kafka binder. The specific exception you are getting is because of the mixed usage of `Message` and `KStream` in your functional example. Let's clear this confusion first, then we can look at the underlying issues.

**Comment by sobychacko** [comment]
This `StreamListener` can be written using the functional style as below.

```
@StreamListener(Sink.INPUT)
public void in(String in, @Header(KafkaHeaders.CONSUMER) Consumer<?, ?> consumer) {
    System.out.println(in);
    consumer.pause(Collections.singleton(new TopicPartition("myTopic", 0)));
}
```

```
@Bean
public java.util.function.Consumer<Message<?>> process() {
    return message -> {
        Consumer<?, ?> consumer = message.getHeaders().get(KafkaHeaders.Consumer, Consumer.class);
        String topic = message.getHeaders().get(KafkaHeaders.Topic, String.class);
        Integer partitionId = message.getHeaders().get(KafkaHeaders.RECEIVED_PARTITION_ID, Integer.class);
        CustomPayload payload = (CustomPayload) message.getPayload();
        if (payload.getRetryTime() < System.currentTimeMillis()) {
            consumer.pause(Collections.singleton(new TopicPartition(topic, partitionId)));
        }
    }
}
```

**Comment by AttitudeL** [comment]
> Hi, @AttitudeL Sorry, we missed your question on StackOverflow. Once we figure this out, we can update the SO question with an answer as well. The functional example you showed above contains `KStream`. Is that intentional? From your `StreamListener` example, it doesn't look like you are using the Kafka Streams binder, but the regular message channel-based Kafka binder. The specific exception you are getting is because of the mixed usage of `Message` and `KStream` in your functional example. Let's clear this confusion first, then we can look at the underlying issues.

Thanks so much for the answer. Due to the the confidential requirement I cannot release the actual code. The reason I had KStream inside the same binding function is because the actual code uses this function to process KStream from other topics.

So if it's not allowed to mix Message and KStream inside the same function I will try separating them out.

Again really appreciate the help. I will give it a try and get back here if everything works. Thanks!

**Comment by AttitudeL** [comment]
> This `StreamListener` can be written using the functional style as below.
> 
> ```
> @StreamListener(Sink.INPUT)
> public void in(String in, @Header(KafkaHeaders.CONSUMER) Consumer<?, ?> consumer) {
>     System.out.println(in);
>     consumer.pause(Collections.singleton(new TopicPartition("myTopic", 0)));
> }
> ```
> 
> ```
> @Bean
> public java.util.function.Consumer<Message<?>> process() {
>     return message -> {
>         Consumer<?, ?> consumer = message.getHeaders().get(KafkaHeaders.Consumer, Consumer.class);
>         String topic = message.getHeaders().get(KafkaHeaders.Topic, String.class);
>         Integer partitionId = message.getHeaders().get(KafkaHeaders.RECEIVED_PARTITION_ID, Integer.class);
>         CustomPayload payload = (CustomPayload) message.getPayload();
>         if (payload.getRetryTime() < System.currentTimeMillis()) {
>             consumer.pause(Collections.singleton(new TopicPartition(topic, partitionId)));
>         }
>     }
> }
> ```

This is a great example! Thanks so much. For the follow question: how can produce the message back to the output topic? From this example it looks like a sink where message doesn't get published to the output topic but in my case after the consumer get resumed it will do the retry and then based on the result either sending the message to the success topic or back to the retry topic if still failing.

**Comment by sobychacko** [comment]
Using the `StreamBridge` API is now preferred to `BinderAwareChannelResolver`. See the [reference docs](https://docs.spring.io/spring-cloud-stream/docs/3.1.1/reference/html/spring-cloud-stream.html#_using_streambridge) for that. Basically, when you resume the consumer, you can use `StreamBridge` to send the record to an outbound destination. If you were using a `Function` instead of a `Consumer`, then the outbound sending is implicitly handled by the framework.

**Comment by AttitudeL** [comment]
@sobychacko really appreciate all the help! Again please allow me sometime (a couple of days tops) to update my code and I will get back here with the result. I will then close the ticket. Thank you so much again!

**Comment by AttitudeL** [comment]
This solution works like a charm! @sobychacko thank you again for all the help! I'm closing this ticket.
