### ISSUE TITLE
Refactor s-c-s samples to use @ConfigurationProperties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-samples#20]
_From @sabbyanandan on November 1, 2015 22:28_

The spring-cloud-streams samples have module options classes copied over from XD.
They should use a pure @ConfigurationProperties approach, making sure metadata is generated/hand written as appropriate.

@Mixins are still referenced there but obviously can't work, so provide an equivalent

_Copied from original issue: spring-cloud/spring-cloud-stream#186_

**Comment by sabbyanandan** [comment]
_From @mbogoevici on November 30, 2015 13:54_

I would rather convert spring-cloud-stream samples into integration tests - which is the way that we are more or less using them. WDYT @sabbyanandan ? cc @markfisher

**Comment by sabbyanandan** [comment]
_From @markpollack on December 1, 2015 2:57_

I'm sure we will eventually have an examples repo, so bite the bullet now?

**Comment by sobychacko** [comment]
Samples repository has changed significantly since opening this issue and therefore closing it.
