### ISSUE TITLE
functional composition using kafka data streams binder does not seem to work

### ISSUE THREAD

**Issue by nmorado** [spring-cloud/spring-cloud-stream-samples#206]
Use this sample code here [functional composition example](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/main/multi-functions-samples/function-composition-kafka) and instead of using stream-binder-kafka use stream-binder-kafka-streams.

The composition on `uppercase|echo` does not seem to work.

**Comment by sobychacko** [comment]
@nmorado  That `uppercase|echo` should work as that is based on regular Kafka binder (`spring-cloud-stream-binder-kafka`). Kafka Streams binder does not allow function composition at the moment and in the next version of the binder we are trying to add that feature on experimental basis.

**Comment by nmorado** [comment]
@sobychacko confirmed that it worked for Kafka binder. thanks for the clarification on the plan of adding function composition to Kafka Streams. thanks
