### ISSUE TITLE
Create example showing schema registry usage

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-samples#21]
As a developer, I'd like to create a sample for schema registry and its usage patterns.

**Acceptance:**
- A simple schema resolution scenario for a processor application is demonstrated
- Project structure, DB configurations and the sample YAML included
- Unit-test procedure documented
- Troubleshooting guide/hints included

**Comment by snoop244** [comment]
I'd contribute a sample if I could, but I can't even get a basic version of this working with either the built-in schema registry or the Avro schema registry.  The docs spend a lot of time describing this, but we really need a working sample.  

I think it needs to show how to work with the built-in schema registry (including how to POST a schema to that registry in the first place as my well-formed JSON keeps being rejected).  I assume it takes Avro schema's (the docs imply this).

Ideally, we would also have a full example based on the Confluent schema registry and Avro schemas for both Source and Sink.  

I'm sorry I couldn't contribute an example myself.  I think SCDF/SCSt + Avro + Kafka is an incredibly powerful combination considering my company's journey towards data-driven microservices.  Schema evolution is a vital use case for us - hence the need for Avro.

**Comment by snoop244** [comment]
I saw the @sobychacko announcement about the updated samples and was hoping a schema registry sample would be available.  Is this still planned?

**Comment by sobychacko** [comment]
@snoop244 We could not make it in the first iteration, but it is still planned. Watch this issue for updates.

**Comment by sabbyanandan** [comment]
@snoop244: Here's a naive take on a [sample](https://github.com/sabbyanandan/schemas). An official work is in progress - stay tuned.

**Comment by sabbyanandan** [comment]
The [official samples](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/schema-registry-samples) are available, too.

**Comment by snoop244** [comment]
This is brilliant!  Thank you!  We believe that schema-as-contract (w. schema evolution) are critical to our decoupled microservices architecture.  Much appreciated!
