### ISSUE TITLE
Can you please update all tutorials to use latest version of Spring Boot?

### ISSUE THREAD

**Issue by javaHelper** [spring-cloud/spring-cloud-stream-samples#220]

**Comment by onobc** [comment]
We are in the process of migrating the samples into the main [spring-cloud-stream](https://github.com/spring-cloud/spring-cloud-stream/tree/main/samples) repo and they will therefore be using the latest version of Boot. 

Note that we are moving them 1-1 so it will take some time for them to all get there. However, we are gladly accepting PR contributions to make the migration quicker, 😄 .
