### ISSUE TITLE
New example for Kafka Streams split (previous branch)

### ISSUE THREAD

**Issue by benkeil** [spring-cloud/spring-cloud-stream-samples#221]
Can you add an example for `split` (the new method how to do branching)?

**Comment by onobc** [comment]
Hi @benkeil ,

I am in the process of updating the current branching sample in this repo and then migrating it to the [new home for the samples](https://github.com/spring-cloud/spring-cloud-stream/tree/main/samples).

In the mean time, the code used by the sample is also available in the ref guide [here](https://docs.spring.io/spring-cloud-stream/docs/4.0.0-M2/reference/html/spring-cloud-stream-binder-kafka.html#_multiple_output_bindings).

**Comment by benkeil** [comment]
Thanks!
