### ISSUE TITLE
Sample application to demonstrate the advanced capabilities of an Aggregate application

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-samples#24]

**Comment by sobychacko** [comment]
Possible features of this application:

* A data Ingester that performs optional processing on the data 

* Support the paradigm of low latency and high throughput 

* This should be a composite of source, one ore more processors and a sink.

* There should not be any middleware technologies in between these individual 
  components in order not to introduce any extra overhead in terms of latency.
  
* The final Sink must send the data to a Kafka topic. 

* The aggregate application should support the option of starting up in various
  source modes. For example, it should be capable of ingesting data from a TCP 
  or UDP source. At the same time, since there is already a Kafka binder in the 
  classpath, (hence kafka client libs) if the application needs to ingest data from
  an external kafka topic, it should be capable of doing so as well. 

* In order to support the above, the aggregate application may need to introduce
  some new features that enables various source modes through some properties at startup. 
  We might have to explore other options for this from a framework point of view, without
  the users writing custom code to handle these scenarios. 

* This aggregate application also should support the model, where the user is able
  to write to multiple sinks without leaving the application itself.

**Comment by sabbyanandan** [comment]
Stale issue; closing it.
