### ISSUE TITLE
Sample using Spring Boot 2.x

### ISSUE THREAD

**Issue by geoand** [spring-cloud/spring-cloud-stream-samples#39]
Hello,

I would appreciate it if you could inform me if there is some sample that uses the Spring Boot 2.x (as of this writing the latest milestone is Spring Boot 2.0.0.M2).
If there is no such sample available, are there any known issues when integrating Spring Cloud Stream and Spring Boot 2.x?

Thank you for your time?
George

**Comment by artembilan** [comment]
I think we can already consider this as duplicated. The Spring Boot/Spring Cloud 2.0 compatibility is addressing in the #54 

Thanks
