### ISSUE TITLE
Create a sample demonstrating schema registry

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-samples#46]
Create a sample demonstrating how our schema registry support works with Avro serialization. This needs to show how one can use our built-in schema registry support as well as Confluent schema registry support. See this test as an example for the latter: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/1.3.x/spring-cloud-stream-binder-kafka-0.10.2-test/src/test/java/org/springframework/cloud/stream/binder/kafka/Kafka_0_10_2_BinderTests.java#L183

**Comment by sabbyanandan** [comment]
Duplicates spring-cloud/spring-cloud-stream-samples#21.
