### ISSUE TITLE
Stream Binding definitions in yml files do not work anymore

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-stream-samples#5]
Running the samples is not possible. Also the tests fail. Affected samples: `sink`, `transform`, `rxjava`. 

Cause is some property definition issue for the stream bindings in application.yml files.
The according error messages look like this:

    Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bindingService' defined in class path resource [org/springframework/cloud/stream/config/ChannelBindingServiceConfiguration.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.springframework.cloud.stream.config.ChannelBindingServiceProperties]: Error creating bean with name 'spring.cloud.stream.CONFIGURATION_PROPERTIES': Could not bind properties to ChannelBindingServiceProperties (prefix=spring.cloud.stream, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
    Field error in object 'spring.cloud.stream' on field 'bindings[input]': rejected value [testtock]; codes [typeMismatch.spring.cloud.stream.bindings[input],typeMismatch.spring.cloud.stream.bindings,typeMismatch.bindings[input],typeMismatch.bindings,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.stream.bindings[input],bindings[input]]; arguments []; default message [bindings[input]]]; default message [Failed to convert property value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BindingProperties] for property 'bindings[input]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BindingProperties] for property 'bindings[input]': no matching editors or conversion strategy found]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.cloud.stream.CONFIGURATION_PROPERTIES': Could not bind properties to ChannelBindingServiceProperties (prefix=spring.cloud.stream, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 1 errors
    Field error in object 'spring.cloud.stream' on field 'bindings[input]': rejected value [testtock]; codes [typeMismatch.spring.cloud.stream.bindings[input],typeMismatch.spring.cloud.stream.bindings,typeMismatch.bindings[input],typeMismatch.bindings,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.stream.bindings[input],bindings[input]]; arguments []; default message [bindings[input]]]; default message [Failed to convert property value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BindingProperties] for property 'bindings[input]'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [org.springframework.cloud.stream.config.BindingProperties] for property 'bindings[input]': no matching editors or conversion strategy found]

It looks as if there was somewhere in the framework stack an update on how to define stream bindings?
When I check the `source` sample (this runs with tests by the way) and check, what is the difference to `sink`, I notice that stream bindings can be defined either this way

    spring:
      cloud:
        stream:
          bindings:
            input: testtock
  
or that way

    spring:
      cloud:
        stream:
          bindings:
            input:
              destination: testtock

First one is the syntax from `sink`, and it causes the failure. Second one is the syntax from `source` which builds perfectly. Changing the syntax also in `sink`, `transform` and `rxjava` to the one using explicit "destination" helps in building these modules with tests.

**Comment by mbogoevici** [comment]
Hi @styjdt,

Sorry for this - we've just made a major change before RC1 but we missed to update the samples. We dropped the syntax without `.destination`.

**Comment by markfisher** [comment]
fixed via https://github.com/spring-cloud/spring-cloud-stream-samples/commit/fabae1c6f486f122b07c4b4e4f68a943f45bb503
