### ISSUE TITLE
Kinesis sample depends on old version of spring-cloud-stream. . .

### ISSUE THREAD

**Issue by olegz** [spring-cloud/spring-cloud-stream-samples#53]
It causes issue described [here](https://github.com/spring-cloud/spring-cloud-stream/issues/1164)

**Comment by amardeepappsbee** [comment]
@olegz Is there any way to run the sample project now.

**Comment by olegz** [comment]
Try to change the POM file to use 2.0.0 snapshot of spring-cloud-stream
```
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream</artifactId>
	<version>2.0.0.BUILD-SNAPSHOT</version>
</dependency>
```

**Comment by amardeepappsbee** [comment]
@olegz After Changing, I am getting following error 

java.lang.NoClassDefFoundError: org/springframework/integration/support/converter/ConfigurableCompositeMessageConverter

**Comment by olegz** [comment]
I've assigned it to @artembilan since he was the primary developer, but given the holidays it may take some time. However, please feel free to investigate further and submit pull request.

**Comment by artembilan** [comment]
The situation is like this Kinesis sample as all here are based on the parent POM and just changing SCSt version here doesn’t help. 

You should change all the dependencies in the parent to the latest 2.0 for Cloud Build. I’m sure many other samples are going to fail after that, but that is only the way to make this Kinesis sample to work.

We might consider to fully upgrade this project to the latest state though...

**Comment by amardeepappsbee** [comment]
After Changing parent pom version to 2.0
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>spring-cloud-stream-samples</artifactId>
	<version>1.2.0.BUILD-SNAPSHOT</version>
	<packaging>pom</packaging>
	<url>https://github.com/spring-cloud/spring-cloud-stream-samples</url>
	<organization>
		<name>Pivotal Software, Inc.</name>
		<url>http://www.spring.io</url>
	</organization>
	<parent>
		<groupId>org.springframework.cloud</groupId>
		<artifactId>spring-cloud-build</artifactId>
		<version>2.0.0.M1</version>
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<spring-cloud-stream.version>Ditmars.BUILD-SNAPSHOT</spring-cloud-stream.version>
		<java.version>1.8</java.version>
	</properties>
	<modules>
		<module>source</module>
		<module>dynamic-source</module>
		<module>sink</module>
		<module>transform</module>
		<module>double</module>
		<module>non-self-contained-aggregate-app</module>
		<module>multibinder</module>
		<module>multibinder-differentsystems</module>
		<module>rxjava-processor</module>
		<module>multi-io</module>
		<module>stream-listener</module>
		<module>reactive-processor-kafka</module>
		<module>test-embedded-kafka</module>
		<module>kinesis-produce-consume</module>
		<module>kstream</module>
		<module>testing</module>
	</modules>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-stream-dependencies</artifactId>
				<version>${spring-cloud-stream.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-stream-sample-source</artifactId>
				<version>2.0.0.BUILD-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-stream-sample-sink</artifactId>
				<version>2.0.0.BUILD-SNAPSHOT</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-stream-sample-transform</artifactId>
				<version>2.0.0.BUILD-SNAPSHOT</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					
					<artifactId>maven-deploy-plugin</artifactId>
					<configuration>
					<skip>true</skip>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
	<profiles>
		<profile>
			<id>spring</id>
			<repositories>
				<repository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>http://repo.spring.io/libs-snapshot-local</url>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
					<releases>
						<enabled>false</enabled>
					</releases>
				</repository>
				<repository>
					<id>spring-milestones</id>
					<name>Spring Milestones</name>
					<url>http://repo.spring.io/libs-milestone-local</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</repository>
				<repository>
					<id>spring-releases</id>
					<name>Spring Releases</name>
					<url>http://repo.spring.io/release</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</repository>
			</repositories>
			<pluginRepositories>
				<pluginRepository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>http://repo.spring.io/libs-snapshot-local</url>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
					<releases>
						<enabled>false</enabled>
					</releases>
				</pluginRepository>
				<pluginRepository>
					<id>spring-milestones</id>
					<name>Spring Milestones</name>
					<url>http://repo.spring.io/libs-milestone-local</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</pluginRepository>
				<pluginRepository>
					<id>spring-releases</id>
					<name>Spring Releases</name>
					<url>http://repo.spring.io/libs-release-local</url>
					<snapshots>
						<enabled>false</enabled>
					</snapshots>
				</pluginRepository>
			</pluginRepositories>
		</profile>
	</profiles>
</project>

getting error 

java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

**Comment by artembilan** [comment]
`2.0.0.M1` is too old. Try to use BUILD-SNAPSHOT.

Would be better to see more stack trace about error.

On the other hand what is the point to stick with this sample? Just create a fresh standalone Spring Boot 2.0 project and do all the Kinesis and streaming stuff already there.

Meanwhile we are considering to switch the master here to 2.0 version with extracting 1.3 branch.

**Comment by chayanappsbee** [comment]
I have already created a standalone project but what should be the spring boot dependency over there. Getting error in using following spring boot dependency.

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.0.0.M1</version>
    <type>pom</type>
</dependency>

What should be the correct dependency

**Comment by chayanappsbee** [comment]
After making a separate Spring Boot Project 2.0.0 BUILD SNAPSHOT its running now 

but when running the jar with following command  

kinesis-produce-consume>$ java -jar target/spring-cloud-stream-sample-kinesis-0.0.1.BUILD-SNAPSHOT.jar --originator=KinesisConsumer --server.port=64399

When I call the rest api its re directs to a login page
which was not there previously 

<html>
    <head>
        <title>Login Page</title>
    </head>
    <body onload='document.f.username.focus();'>
        <h3>Login with Username and Password</h3>
        <form name='f' action='/login' method='POST'>
            <table>
                <tr>
                    <td>User:</td>
                    <td>
                        <input type='text' name='username' value=''>
                    </td>
                </tr>
                <tr>
                    <td>Password:</td>
                    <td>
                        <input type='password' name='password'/>
                    </td>
                </tr>
                <tr>
                    <td colspan='2'>
                        <input name="submit" type="submit" value="Login"/>
                    </td>
                </tr>
            </table>
        </form>
    </body>
</html>

**Comment by artembilan** [comment]
That's true, @chayanappsbee .

There is a security in Spring Boot Web application enabled by default.

You can consider to use the generated user/password - you can see them in the logs during application start up. Or you can consider to disable security altogether.

All the info on the matter is in the Spring Boot Reference Manual: 

https://docs.spring.io/spring-boot/docs/2.0.0.M7/reference/htmlsingle/#boot-features-security

https://docs.spring.io/spring-boot/docs/2.0.0.M7/reference/htmlsingle/#howto-switch-off-spring-boot-security-configuration


Or just comment out `spring-boot-starter-security` dependency in this sample's POM...

**Comment by chayanappsbee** [comment]
@artembilan Commented out spring-boot-starter-security.
Its working fine now.
Thanks

**Comment by spjegan** [comment]
Can someone please share the pom file with the correct dependencies? I was able to build a separate project and start the application with 2.0.0.BUILD-SNAPSHOT. But when I fire the curl commands, I do not see any log messages other than below on both producer and consumer.

```
2018-01-04 10:18:36.923  INFO 61312 --- [io-64398-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring FrameworkServlet 'dispatcherServlet'
2018-01-04 10:18:36.924  INFO 61312 --- [io-64398-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization started
2018-01-04 10:18:36.943  INFO 61312 --- [io-64398-exec-1] o.s.web.servlet.DispatcherServlet        : FrameworkServlet 'dispatcherServlet': initialization completed in 19 ms
```

**Comment by spjegan** [comment]
Got it. Disabling spring-security made it work. Thanks for the help.

**Comment by artembilan** [comment]
Glad to hear that @spjegan !

We definitely have plans to move all these samples to Spring Cloud Stream 2.0.
