### ISSUE TITLE
Update master to Spring Cloud Stream 2.0

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-samples#54]
As a developer, I'd like to update all the samples in the `master` branch to 2.0.

**Acceptance:**
- Decide between parent-pom vs. standalone application with its dependencies
- Update `master` to be on 2.0 for all the apps (1.3 _must_ continue on SCSt 1.3.x)
- Verify [`master`](https://jenkins.spring.io/view/SpringCloudStream/view/CI/job/spring-cloud-stream-samples-master-ci/) and [`ditmars`](https://jenkins.spring.io/view/SpringCloudStream/view/CI/job/spring-cloud-stream-samples-Ditmars-ci/) CI plans continue to build on incremental commits
- Verify CI plan is a child of SCSt core/binder plans

**Comment by sobychacko** [comment]
We need to convert each of these samples to its own application

- [ ] double
- [ ] dynamic-source
- [ ] kinesis-produce-consume
- [ ] kstream
- [ ] multi-io
- [ ] multibinder-differentsystems
- [ ] multibinder 
- [ ] non-self-contained-aggregate-app
- [ ] reactive-processor-kafka
- [ ] rxjava-processor
- [ ] test-embedded-kafka
- [ ] testing
- [ ] transform

**Comment by sobychacko** [comment]
All samples are updated.
