### ISSUE TITLE
getting NoClassDefFoundError: org/springframework/tuple/spel/Tuple PropertyAccessor while trying to run kinesis-produce-consume application

### ISSUE THREAD

**Issue by vikrantch-hk** [spring-cloud/spring-cloud-stream-samples#56]
Hi Team,

I am trying to run kinesis-produce-consume application by following steps mentioned in README file, I am getting below error 

2018-02-11 17:51:36.882  WARN 6504 --- [           main] ationConfigEmbeddedWebA
pplicationContext : Exception encountered during context initialization - cancel
ling refresh attempt: org.springframework.beans.factory.BeanCreationException: E
rror creating bean with name 'propertyAccessorBeanPostProcessor' defined in clas
s path resource [org/springframework/cloud/stream/config/BindingServiceConfigura
tion$PostProcessorConfiguration.class]: Bean instantiation via factory method fa
iled; nested exception is org.springframework.beans.BeanInstantiationException:
Failed to instantiate [org.springframework.beans.factory.config.BeanPostProcesso
r]: Factory method 'propertyAccessorBeanPostProcessor' threw exception; nested e
xception is java.lang.NoClassDefFoundError: org/springframework/tuple/spel/Tuple
PropertyAccessor
2018-02-11 17:51:36.894 ERROR 6504 --- [           main] o.s.b.f.s.DefaultListab
leBeanFactory     : Destroy method on bean with name 'org.springframework.boot.c
ontext.properties.ConfigurationPropertiesBindingPostProcessor' threw an exceptio
n

**Comment by artembilan** [comment]
I think your problem is clearly described here #53 - the Kinesis Binder sample must be tested against Spring Cloud Stream `2.0`.

**Comment by vikrantch-hk** [comment]
thanks for quick response, it worked :)
