### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by dodalovic** [spring-cloud/spring-cloud-stream-samples#59]
![image](https://user-images.githubusercontent.com/6358061/36383005-1dd4c482-158b-11e8-8abc-55ee28f76378.png)

**Comment by sobychacko** [comment]
Hi @dodalovic - we are revamping the samples project structure this week. In the meantime, can you comment out this line and try your build? https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/pom.xml#L40
Thanks!

**Comment by dodalovic** [comment]
I'll just wait for you to revamp. thx
