### ISSUE TITLE
Build fails due to some change of dependency management in parent projects

### ISSUE THREAD

**Issue by styjdt** [spring-cloud/spring-cloud-stream-samples#7]
I don't know, how to really develop against snapshot repositories, perhaps I'm doing something wrong. Today the samples projects don't build due to

```
[ERROR]   The project org.springframework.cloud:spring-cloud-stream-sample-source:1.0.0.BUILD-SNAPSHOT (C:\Users\D053139\git\spring-cloud-stream-samples\source\pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.springframework.cloud:spring-cloud-stream-binder-redis:jar is missing. @ org.springframework.cloud:spring-cloud-stream-sample-source:[unknown-version], C:\Users\D053139\git\spring-cloud-stream-samples\source\pom.xml, line 25, column 15
```

And that error message for each of the top level and the single sample projects...

Fixing the version of spring-cloud-stream-binder-redis manually to 1.0.0.BUILD-20160317.060453-286 in all affected modules helps. But surely this is not the way how to solve such issues?

**Comment by mbogoevici** [comment]
Hi @styjdt,

Unfortunately we didn't update the build after we moved the Redis binder out of Spring Cloud Stream. Please try the latest master.

Thanks,
Marius

**Comment by styjdt** [comment]
Hi Marius,
now everything works.
So if I understand correctly, in such cases I cannot do much, but tell you to update your builds? Or is there any way for me as developer to "protect" me against such situations?
Or is it purely a question of your build system? :smile: 
Alexander

**Comment by mbogoevici** [comment]
No, this was an oversight. Thanks for reporting it.

**Comment by sobychacko** [comment]
Samples repository has changed significantly since opening this issue and therefore closing it. Please ping back here if problems still persist.
