### ISSUE TITLE
Add e2e SNAPSHOT tests against cloud platforms

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-samples#71]
_From @sabbyanandan on January 3, 2018 15:32_

As a developer, I'd like to add/improve IT test coverage to test standalone SCSt apps on cloud platforms. 

**Acceptance:**
- The goal is to run SNAPSHOTs of the standalone apps on:
   - [x] CF 
   - [ ] K8S
- We could follow the similar infrastructure in place for [SCDF's acceptance tests](https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests), but run the apps in isolation; independently via a different CI plan.
- Consider a CI plan for both the recent release-branch and as well as for `master`.

_Copied from original issue: spring-cloud/spring-cloud-stream-starters#43_

**Comment by sobychacko** [comment]
This issue was moved to spring-cloud/spring-cloud-stream-acceptance-tests#4
