### ISSUE TITLE
test embedded kafka with 2.0.3 release

### ISSUE THREAD

**Issue by srinivasvsk** [spring-cloud/spring-cloud-stream-samples#77]
Having trouble getting the tests run when i use it with the released versions of spring boot 2.0.3, cloud stream 2.0.0.release.
Are the sample missing some additional configuration

Thanks

**Comment by olegz** [comment]
Please explain the type of "trouble" you are having. We can't possibly presume anything from your description.

**Comment by srinivasvsk** [comment]
Sorry meant to say the test doesnt pass,  the Stream listener never receives the message so the asserts below fail

`Consumer<byte[], byte[]> consumer = cf.createConsumer();
		consumer.subscribe(Collections.singleton(OUTPUT_TOPIC));
		ConsumerRecords<byte[], byte[]> records = consumer.poll(10_000);
		consumer.commitSync();

		assertThat(records.count()).isEqualTo(1);
		assertThat(new String(records.iterator().next().value())).isEqualTo("FOO");`

**Comment by olegz** [comment]
I am afraid you did not provide any more clarity then before. Can you please specify which specific example in _spring-cloud-stream-samples_ you are referring to?

**Comment by srinivasvsk** [comment]
I was trying this sample code in a different project with released artifacts.
https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/testing-samples/test-embedded-kafka/src

Attaching the code below as well,

[demo.cloud.stream.zip](https://github.com/spring-cloud/spring-cloud-stream-samples/files/2131275/demo.cloud.stream.zip)

**Comment by sabbyanandan** [comment]
Hi, @srinivasvsk. If you have issues with the samples in its current state, please share the specifics of what that is. If you've general problems on your custom App, this is not the right forum to discuss that. You can start the conversation in Gitter or StackOverflow.
