### ISSUE TITLE
Error when use kafka-avro-console-consumer consume avro message sent by spring cloud stream kafka

### ISSUE THREAD

**Issue by ChenShuai1981** [spring-cloud/spring-cloud-stream-samples#90]
Hi, I tried schema-registry-confluent example (consumer/producer) with my installed confluent 4.0.0, it can send "sensor" avro message when send post request and receive in listener, but when I use kafka-avro-console-consumer tool shipped with confluent to view avro message sent, the tool raised the following error (a). I also tried to consume avro message sent by kafka-avro-console-producer tool (and the message can be shown correctly in kafka-avro-console-consumer tool) , it reported the following error (b). Doesn't the given example support confluent 4.0.0? 

(a) kafka-avro-console-consumer error =>
> ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$:107)
> org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
> Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!

(b) listener error =>
> org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Invalid UTF-32 character 0x51473863 (above 0x0010ffff) at char #1, byte #7); nested exception is java.io.CharConversionException: Invalid UTF-32 character 0x51473863 (above 0x0010ffff) at char #1, byte #7)
>         at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:234) ~[spring-messaging-5.1.0.BUILD-SNAPSHOT.jar!/:5.1.0.BUILD-SNAPSHOT]
>

**Comment by LeonardoBonacci** [comment]
idem

**Comment by sobychacko** [comment]
First of all, apologies for not getting back on this issue. Your observations are right. Basically, here is the gist of the problem. When using the combination of Confluent Schema Registry and Spring Cloud Stream Avro converters (serializer/deserializer), then you can only use your producers with a Spring Cloud Stream consumer that's using the same `ScSt` Avro converter. External tools like `kafka-avro-console-consumer` or `kafka-avro-console-producer ` won't work with these apps. This is the reason you got both of the errors mentioned above. Even if you use a regular Java producer (standalone or using something like spring-kafka) with the Confluent Avro serializer and then try to use the consumer in this sample, that will fail as the serializers are not compatible. 

There are 2 ways to fix this problem.

1. Make a change in the `ScSt` Avro converters to inject external serializers somehow. Then the applications can provide a bean of type Confluent's Avro serializer which takes precedence in the scst converter. This is not possible currently, and we could potentially make this change if this becomes a common use case.
2. Another practical possibility is to use the Confluent Avro serializers all throughout the components using native encoding and decoding. Unless you have a specific requirement to use the ScSt avro converters, this is a strategy that you can definitely pursue. [Here](https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/schema-registry-samples/schema-registry-confluent-avro-serializer) is a sample that demonstrates this strategy. Take a look at the README and the configurations in each component.

**Comment by ChenShuai1981** [comment]
Thank you, sobychacko. I tried your suggestion and it works well now. :-)
