### ISSUE TITLE
Kafka example publishes and consumes to/from different topics

### ISSUE THREAD

**Issue by adyach** [spring-cloud/spring-cloud-stream-samples#91]
I have touched the example test https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/testing-samples/test-embedded-kafka/src/test/java/demo/EmbeddedKafkaApplicationTests.java, and it happened that it uses different topics for for publishing and consumption. Was it done like that on purpose?

**Comment by adyach** [comment]
Also what was sent does not much to what is expected

**Comment by sobychacko** [comment]
@adyach Please see my comment on your [PR](https://github.com/spring-cloud/spring-cloud-stream-samples/pull/92#issuecomment-419197110).
