### ISSUE TITLE
Add a sample demonstrating GlobalKTable using kafka streams binder

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/spring-cloud-stream-samples#93]

**Comment by todaynowork** [comment]
Hi Sobychacko,
When do you think we could see a demo of GlobalKTable? Now I want to check KStream join with GlobalKTable, but can not find any sample. If you already have one, could you kindly share it with me.
Thanks,
Du

**Comment by rksharma82** [comment]
I am looking for the same it will be helpful. Please share if you have created one already.

**Comment by todaynowork** [comment]
I have created one simple demo. You could take a look at [global-ktable-join](https://github.com/todaynowork/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-global-table-join).

I also created one that use object as key to join, not uploaded yet. If you want, I could clean and upload.

**Comment by sobychacko** [comment]
@todaynowork Could you please send that as a PR against this repository? We will then review it. Thanks a lot of creating the sample.
